version: '3.8'

services:
  excel-pdf-converter:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./Pro Forma (4 Products).xlsx:/app/sample.xlsx:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8501/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development service with live reload
  excel-pdf-converter-dev:
    build: .
    ports:
      - "8502:8501"
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - DEBUG=true
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.runOnSave=true"]
    profiles:
      - dev
