name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test Streamlit app
      run: |
        python -c "import streamlit_app; print('Streamlit app imports successfully')"
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Streamlit Cloud deployment will be triggered automatically"
        echo "Make sure your repository is connected to Streamlit Cloud"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
